# Generated by Django 4.1.7 on 2023-04-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=75)),
                ("region", models.CharField(max_length=75)),
                ("latitude", models.CharField(max_length=75)),
                ("longitude", models.CharField(max_length=75)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
