# Generated by Django 4.1.7 on 2023-04-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, unique, max-255",
                        max_length=15,
                        unique=True,
                        verbose_name="brand name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="format: required, letters, numbers, underscore, or hyphens",
                        max_length=150,
                        verbose_name="Brand safe URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50, verbose_name="Device name")),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Device version",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="format: required, letters, numbers, underscores or hyphens",
                        max_length=255,
                        verbose_name="Device safe URL",
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        default="",
                        help_text="format: required",
                        verbose_name="Device description",
                    ),
                ),
                (
                    "released",
                    models.DateTimeField(
                        blank=True,
                        help_text="format: Y-m-d H:M:S",
                        null=True,
                        verbose_name="Date Device released",
                    ),
                ),
                (
                    "announced",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="format: Y-m-d H:M:S",
                        null=True,
                        verbose_name="Date Device announced",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.brand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, unique, max-255",
                        max_length=255,
                        unique=True,
                        verbose_name="Device attribute name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="format: required",
                        verbose_name="Device attribute description",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_value",
                    models.CharField(max_length=255, verbose_name="attribute value"),
                ),
                (
                    "Device_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Device_attributes",
                        to="devices.deviceattribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, max-100",
                        max_length=100,
                        verbose_name="category name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="format: required, letters, numbers, underscore, or hyphens",
                        max_length=150,
                        verbose_name="category safe URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devices category",
                "verbose_name_plural": "Devices categories",
            },
        ),
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="format: required, unique, max-255",
                        max_length=255,
                        unique=True,
                        verbose_name="type of Device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        default="images/default.png",
                        help_text="format: required, default-default.png",
                        verbose_name="Device image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=255, verbose_name="alternative text"),
                ),
                (
                    "is_feature",
                    models.BooleanField(
                        default=False,
                        help_text="format: default=false, true=default image",
                        verbose_name="Device default image",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "Device image",
                "verbose_name_plural": "Device images",
            },
        ),
        migrations.CreateModel(
            name="DeviceTypeAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Device_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Device_attribute",
                        to="devices.deviceattribute",
                    ),
                ),
                (
                    "Device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Device_type",
                        to="devices.devicetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("Device_attribute", "Device_type")},
            },
        ),
        migrations.AddField(
            model_name="devicetype",
            name="Device_type_attributes",
            field=models.ManyToManyField(
                related_name="Device_type_attributes",
                through="devices.DeviceTypeAttribute",
                to="devices.deviceattribute",
            ),
        ),
        migrations.CreateModel(
            name="DeviceSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "web_id",
                    models.CharField(max_length=40, verbose_name="Device website ID"),
                ),
                (
                    "source",
                    models.CharField(max_length=40, verbose_name="Device website ID"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.devicecategory"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="It can be used to form the table of content of the parent post of series.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="devices.device",
            ),
        ),
        migrations.CreateModel(
            name="DeviceAttributeValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute_values",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attribute_values",
                        to="devices.deviceattributevalue",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_values", "device")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("model", "version")},
        ),
    ]
