# Generated by Django 4.1.7 on 2023-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceattribute",
            name="attribute",
            field=models.CharField(max_length=50, verbose_name="attribute"),
        ),
    ]
