# Generated by Django 4.1.7 on 2023-05-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("new inserted", "New Inserted"),
                    ("updated once", "Updated Once"),
                    ("updated twice", "Updated twice"),
                ],
                default="new inserted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="devicesource",
            name="source",
            field=models.CharField(max_length=40, verbose_name="Device source"),
        ),
    ]
