# Generated by Django 4.1.7 on 2023-05-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_device_unique_together_device_mpn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mpn",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Device version"
            ),
        ),
    ]
