# Generated by Django 4.1.7 on 2023-04-16 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Email must be entered in the format: `abc@abc.com`.",
                        regex="^[A-z0-9\\.]+@[A-z0-9]+\\.(com|net|org|info)$",
                    )
                ],
                verbose_name="email address",
            ),
        ),
    ]
