# Generated by Django 4.1.7 on 2023-04-14 11:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Article Title",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        help_text="The meta title to be used for browser title and SEO.",
                        max_length=255,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The article slug to form URL.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="The description of the article to mention the key highlights.",
                        max_length=1015,
                        verbose_name="Description",
                    ),
                ),
                ("content", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("country", models.CharField(default="", max_length=15)),
                ("language", models.CharField(default="", max_length=15)),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="It stores the date and time at which the article is Published.",
                        verbose_name="Published At",
                    ),
                ),
                (
                    "reading_times",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Increasing positive number to calculate the reading times.",
                        verbose_name="Reading Times",
                    ),
                ),
                (
                    "trending",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Increasing positive number to calculate the reading times.",
                        verbose_name="Trending",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="format: required, max-100",
                        max_length=100,
                        unique=True,
                        verbose_name="category name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="format: required, letters, numbers, underscore, or hyphens",
                        max_length=150,
                        unique=True,
                        verbose_name="The category slug to form URL.",
                    ),
                ),
            ],
            options={
                "verbose_name": "article category",
                "verbose_name_plural": "article categories",
            },
        ),
        migrations.CreateModel(
            name="ArticleMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The key identifying the meta.",
                        max_length=50,
                        verbose_name="Key",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The column used to store the article data.",
                        verbose_name="Key",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                related_name="categories", to="articles.category"
            ),
        ),
    ]
